import { useState } from "react";
import type { GetServerSideProps } from "next";
import Head from "next/head";
import { Session } from "next-auth";
import { getSession, GetSessionParams, useSession } from "next-auth/react";
import LoginButton from "../components/login-btn";
import { isValidAddress } from "../utils/isValidAddress";
import { hasClaimed } from "./api/claim/status";
import Button from "../components/button";
import WalletInput from "../components/wallet-input";

type Props = {
  claimed: boolean;
};

const Home = ({ claimed }: Props) => {
  const { status } = useSession();
  const [address, setAddress] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  /**
   * Process faucet drip request
   */
  const processDrip = async () => {
    // Toggle loading
    setLoading(true);

    try {
      console.log("yoo");

      // Post new claim with recipient address
      fetch("/api/claim/new", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ address }),
      });
    } catch (error: unknown) {
      console.log("Error:", error);
    }

    // try {
    //   // Post new claim with recipient address
    //   await axios.post("/api/claim/new", { address, others: claimOther });
    //   // Toast if success + toggle claimed
    //   toast.success("Tokens dispersed—check balances shortly!");
    //   setClaimed(true);
    //   setFirstClaim(true);
    // } catch (error: any) {
    //   // If error, toast error message
    //   toast.error(error.response.data.error);
    // }

    // Toggle loading
    setLoading(false);
  };

  return (
    <div className="max-w-7xl h-screen mx-auto px-4 sm:px-6 lg:px-8">
      <Head>
        <title>Faucet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl mx-auto">
        <h2 className="text-center pt-12 text-3xl leading-8 font-bold tracking-tight text-gray-900 sm:text-4xl sm:tracking-tight">
          Polkadot Faucet
        </h2>
        <p className="mt-2 max-w-3xl mx-auto text-center text-xl text-gray-500">
          Bootstrap your testnet wallet
        </p>

        <div className="mt-12 bg-white shadow border border-gray-300 sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-lg leading-6 font-medium text-gray-900">
              Request Tokens
            </h3>

            {status === "authenticated" && (
              <>
                <p className="mt-2 text-sm text-gray-500">
                  Enter your wallet address to receive testnet tokens.
                </p>

                <form className="mt-5">
                  <WalletInput
                    value={address}
                    onChange={(evt: React.ChangeEvent<HTMLInputElement>) =>
                      setAddress(evt.target.value)
                    }
                  />

                  {isValidAddress(address) ? (
                    // If address is valid, allow claiming
                    <Button onClick={processDrip} disabled={loading}>
                      {!loading ? "Claim" : "Claiming ..."}
                    </Button>
                  ) : (
                    // Else, force to fix address
                    <Button disabled>
                      {address === ""
                        ? "Enter valid address"
                        : "Invalid address"}
                    </Button>
                  )}

                  <LoginButton />
                </form>
              </>
            )}

            {status !== "authenticated" && (
              <>
                <p className="mt-2 text-gray-900">
                  To prevent faucet abuse, you must sign in with Twitter or
                  GitHub.
                </p>

                <LoginButton />
              </>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export async function getServerSideProps(context: GetServerSideProps) {
  const session: Session | null = await getSession(context as GetSessionParams);

  return {
    props: {
      session,
      claimed: session ? await hasClaimed(session) : false,
    },
  };
}

export default Home;
